### ISSUE TITLE
Issue with CURLOPT_FOLLOWLOCATION => true

### ISSUE THREAD

**Issue by cdharrison** [bendodson/WallaBee-API-PHP-Wrapper#1]
In CURL.class.php I had to change `CURLOPT_FOLLOWLOCATION => true` to `CURLOPT_FOLLOWLOCATION => false` in order to get this to work with my host (MediaTemple). Just thought I'd mention it in case anyone else runs into issues.

Thanks for providing this. I'm still figuring my way around it, but have already started building a few things out using the data that I hope to include on http://itembrowser.com. (The set information is already being pulled via the API.)

**Comment by bendodson** [comment]
Just going through my old repos and found this issue. I'm gonna go ahead and close it as assume it is now fixed lol.
